# Docker Compose for SDN Lab
services:
  # Define a "controller" service
  controller:
    image: martimy/ryu-flowmanager
    environment:
     - NETWORK_CONFIG_FILE=scripts/network_config.yaml
     - GRAPHITE_SERVER=graphite
     - GRAPHITE_POLLTIME=15
     - INFLUXDB_HOST=influxdb
#    command: "scripts/dc_switch_1.py --observe-links"
    command: "scripts/dc_switch_3.py scripts/monitor_influxdb.py --observe-links"
    command: "scripts/dc_switch_3.py scripts/monitor_prometheus.py --observe-links"
    volumes:
     - ./scripts:/home/auser/scripts
    ports:
     - "6633"  # Controller port
     - "6653"  # Controller port
     - "8080:8080"  # GUI port

  # Define a "mininet" service
  mininet:
    image: martimy/mininet
    depends_on: # In this case only
     - controller
    tty: true # Allocates a pseudo-TTY (teletypewriter) for the container
    privileged: true # required for mininet to run inside a container
    environment:
     - SDN_CONTROLLER=controller
     - HISTFILE=/root/scripts/.bash_history
      #  DISPLAY  # Passes the value of the DISPLAY environment variable to the container
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix    # Mounts X11 socket for GUI access
     - /lib/modules:/lib/modules        # Mounts kernel modules from the host to the container
     - ./scripts:/root/scripts

  # Define a "Graphite" service
  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
     - ./graphite/conf:/opt/graphite/conf
     - ./graphite/storage:/opt/graphite/storage
    ports:
     - "2003-2004"
     - "2023-2024"
     - "9000:80"

  # Define a "Prometheus" service
  prometheus:
    image: prom/prometheus
    volumes:
     - ./scripts/prometheus.yaml:/etc/prometheus/prometheus.yml
     - ./prometheus:/prometheus
    ports:
     - "9090:9090"

  # Define a "InfluxDB" service
  influxdb:
    image: influxdb:1.8
    volumes:
     - ./influxdb/data:/var/lib/influxdb2" \
     - ./influxdb/config:/etc/influxdb2" \
    ports:
     - "8086:8086"
