# Docker Compose version 3
version: '3'

services:
  # Define a service named "mininet"
  mininet:
    image: martimy/mininet
    tty: true # Allocates a pseudo-TTY (teletypewriter) for the container
    privileged: true # required for mininet to run inside a container
    environment:
      HISTFILE: /root/.bash_history
      #  DISPLAY  # Passes the value of the DISPLAY environment variable to the container
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix    # Mounts X11 socket for GUI access
     - /lib/modules:/lib/modules        # Mounts kernel modules from the host to the container
     - ./scripts:/root/scripts
    network_mode: "host"

  # Define a service named "flowmanager"
  flowmanager:
    image: martimy/ryu-flowmanager
    command: "${FLOW_CMD}" # example: scripts/learning_switch_2.py
    volumes:
     - ./scripts:/home/auser/scripts
    #ports:
    #  - 6633:6633
    #  - 6653:6653
    #  - 8080:8080
    network_mode: "host"
