# Docker Compose for SDN Lab
services:
  # Define a "flowmanager" service
  flowmanager:
    image: martimy/ryu-flowmanager
    environment:
      - NETWORK_CONFIG_FILE=scripts/network_config.yaml
    command: "scripts/dc_switch_1.py --observe-links"
    volumes:
     - ./scripts:/home/auser/scripts
    ports:
     - "6653:6653"  # Controller port
     - "6633:6633"  # Controller port
     - "8080:8080"  # GUI port

  # Define a "mininet" service
  mininet:
    image: martimy/mininet
    depends_on: # In this case only
      - flowmanager  
    tty: true # Allocates a pseudo-TTY (teletypewriter) for the container
    privileged: true # required for mininet to run inside a container
    environment:
      SDN_CONTROLLER: flowmanager
      HISTFILE: /root/scripts/.bash_history
      #  DISPLAY  # Passes the value of the DISPLAY environment variable to the container
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix    # Mounts X11 socket for GUI access
     - /lib/modules:/lib/modules        # Mounts kernel modules from the host to the container
     - ./scripts:/root/scripts

  # Define a "Graphite" service
  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
     - ./graphite/conf:/opt/graphite/conf
     - ./graphite/storage:/opt/graphite/storage
    ports:
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "9000:80"
