---
switches:
  - name: s11
    id: 11
    type: spine
  - name: s12
    id: 12
    type: spine
  - name: s21
    id: 21
    type: leaf
  - name: s22
    id: 22
    type: leaf
  - name: s23
    id: 23
    type: leaf

hosts:
  - name: h1
    ip: 10.1.1.1
    mac: 00:00:00:00:00:01
    default_route: "via 10.1.1.100"
    connected_to: s21
    port: 3
  - name: h2
    ip: 10.1.1.2
    mac: 00:00:00:00:00:02
    default_route: "via 10.1.1.100"
    connected_to: s21
    port: 4
  - name: h3
    ip: 10.1.1.3
    mac: 00:00:00:00:00:03
    default_route: "via 10.1.1.100"
    connected_to: s22
    port: 3
  - name: h4
    ip: 10.1.1.4
    mac: 00:00:00:00:00:04
    default_route: "via 10.1.1.100"
    connected_to: s22
    port: 4
  - name: h5
    ip: 10.1.1.5
    mac: 00:00:00:00:00:05
    default_route: "via 10.1.1.100"
    connected_to: s23
    port: 3
  - name: h6
    ip: 10.1.1.6
    mac: 00:00:00:00:00:06
    default_route: "via 10.1.1.100"
    connected_to: s23
    port: 4

links:
  - source: s11
    source_port: 1
    target: s21
    target_port: 1
  - source: s11
    source_port: 2
    target: s22
    target_port: 1
  - source: s11
    source_port: 3
    target: s23
    target_port: 1
  - source: s12
    source_port: 1
    target: s21
    target_port: 2
  - source: s12
    source_port: 2
    target: s22
    target_port: 2
  - source: s12
    source_port: 3
    target: s23
    target_port: 2
