# Prometheus configuration file

global:
  scrape_interval: 15s

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
  - job_name: 'ryunet'
    static_configs:
      - targets: ['localhost:8088']
